$(document).ready(function() {
  var list;
  // Block#: agK8;bQ_r@U5FJy;tbf(
  function on_listview_length_configured_ListView() {
    try {
      // Block#: j]FS?~RJ(Z2{o_,x|j~@
      list = ['Hi', 'Hola', 'Hello'];
      com.fc.JavaScriptDistLib.ListView.configureCells('ListView', list.length);
      $('[obj-name="ListView"]').children().each(function(i) {
        if(i > 0) {
          com.fc.JavaScriptDistLib.ListView.setContext($(this));
          com.fc.JavaScriptDistLib.ListView.executeConfigCallback('ListView', i - 1);
          //let currName = $(this).attr("obj-name");
          //on_listview_cell_configured_ListView($(this), i-1);
          com.fc.JavaScriptDistLib.ListView.resetContext($(this));
        }
      });
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  var element = document.querySelector('[obj-name="ListView"]');
  if(window.IntersectionObserver) {
    var observer = new IntersectionObserver(function(entries) {
      if(entries[0].intersectionRatio) {
        console.log('visible ListView');
        on_listview_length_configured_ListView();
      } else {
        console.log('hidden');
      }
    }, {
      root: document.body
    });
    observer.observe(element);
  }
  // Block#: Q%*?t{HD:.)ld@]xo2tc
  function on_listview_cell_configured_ListViewCell(ListViewCell, number) {
    try {
      // Block#: s%/64Ow~~ksX*y[1Z1T2
      if(number == 0) {
        // Block#: *VV~EUKAYy~NxRwS_fN,
        com.fc.JavaScriptDistLib.ListView.setProperty["Background color"](ListViewCell, '#ff0000');
      }
      // Block#: |YE;uI6-(m9MW}vyTn4}
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Label", (list[number]));
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  com.fc.JavaScriptDistLib.ListView.setConfigCallback('ListViewCell', on_listview_cell_configured_ListViewCell);
  // Block#: 5?Kb^g?*:~7Aycwi8ka.
  // Block#: l/D^tfAPUgKO$3-`xBbZ
  function on_Button_click(e) {
    try {
      // Block#: vP=]HF--WGC0R)MHKjgQ
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="Button"]').on('click', on_Button_click);
  $('[obj-name="MainScreen"]').show();
});
// Generated by snapp
// 291318-592906-937699-533492
